spring:
  application:
    name: niwotest-service
  cloud:
    nacos:
      config:
        server-add: 172.16.0.165:8848
      discovery:
        server-addr: 172.16.0.165:8848
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 172.16.0.100
    port: 5672
    username: admin
    password: 123456
    listener:
      direct:
        prefetch: 10
