spring:
  application:
    name: commission-new-service
  zipkin:
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.13.3.225:3306/commission?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: Xa612I77Kvi
    druid:
      #filters: stat,wall,stat,slf4j,default
      filters: slf4j,default
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: test
        login-password: 123456
#      filter:
#        slf4j:
#          enabled: true
#          resultSetLogEnabled: false
#          statementCreateAfterLogEnabled: false
#          statementExecutableSqlLogEnable: true
#          statementLogEnabled: true
  redis:
    redisson:
      pingConnectionInterval: 1000
      password: n9CaqMmHuA6xoIu6
      address: redis://10.13.3.225:6379
    database: 0
    host: 10.13.3.225
    port: 6379
    password: n9CaqMmHuA6xoIu6
    timeout: 300000ms
    lettuce:
      pool:
        max-active: 8
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  logging:
    level:
      druid:
        sql:
          statement: debug
logging:
  level:
    druid:
      sql:
        statement: debug
    com.jubaozan.service.commission.**: DEBUG
    com.jubaozan.service.commission.domain.**.mapper.**: DEBUG
  #config: classpath:logback-spring.xml


mybatis-plus:
  mapper-locations: "classpath*:mybatis/*/*.xml"
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
  partition:
    sjids:
      - 997
    tableNames:
      - fx_agent
    always:
      target-schema: data_stats


