spring:
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #配置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 172.16.0.100
                port: 5672
                username: admin
                password: 123456
      bindings: #服务的整合处理
        #        output: #这个名字是一个通道的名称
        #          destination: studyExchange #表示使用的exchange名称定义
        #          content-type: application/json #设置消息类型，本次为json，文本则设置"text/plain"
        #          binder: defaultRabbit #设置要绑定的消息服务的具体设置
        springCloudBusInput:
          destination: sz
          group: workflow
        springCloudBusOutput:
          destination: sz

    bus:
      enabled: true
      trace:
        enabled: true